### ISSUE TITLE
DEVELOPER TASK: Marketing

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/wherearewegoing#21]
## Description: 
Create the files and meta tags to improve the website's search engine optimization (SEO).

## Acceptance Criteria:
* Acceptance Criteria 1: I have the robots.txt file.
* Acceptance Criteria 2: I have the sitemap.xml file.
* Acceptance Criteria 3: I have the meta tags.

## Tasks
- [ ] Task 1: Add robots.txt.
- [ ] Task 2:Add sitemap.xml.
- [ ] Task 3:Add meta tags.
