### ISSUE TITLE
USER STORY: Preferences

### ISSUE THREAD

**Issue by BohdanBezushka** [BohdanBezushka/wherearewegoing#5]
As a **user**, I can **sort festivals by date, country, and price** so that **I can easily find and select festivals based on my preferences.**

## Acceptance Criteria:
* Acceptance Criteria 1: The user can view festivals according to date.
* Acceptance Criteria 2: The user can view festivals according to country.
* Acceptance Criteria 3: The user can view festivals according to price.

## Tasks
- [ ] Task 1: Add sorting by date.
- [ ] Task 2: Add sorting by country.
- [ ] Task 3: Add sorting by price.
